# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b07cff9ab964b89152d81905d1604a23e2223c31054a85cf402debc34bc70c8381d6c0ddf3f7472b38ab50ce38d3471caca13c021ad9030bb5e67a7039df7b67

test:
  secret_key_base: d0a3d8fa05eea8f64917fc3d46800ca4c0a7008c556f58b82f0531dadca201da2d5ff0ad9b430fa1f1bb4a6af045acac3abfe0aacbff9200b014614f42cd7f30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
